#Specify version number
version: '3.7'

volumes:
  data94:
    driver_opts:
      type: none
      device: /opt/pgupg94to12/volumes/data94
      o: bind
  data12:
    driver_opts:
      type: none
      device: /opt/pgupg94to12/volumes/data12
      o: bind

services:
  #Specify service
  postgres94:
    image: docker.io/library/postgres:9.4
    environment:
     - POSTGRES_PASSWORD=23894idhfkasjdhkhioydifad
    volumes:
     - data94:/var/lib/postgresql/data
    ports:
     - 5432:5432
  postgres12:
    image: docker.io/library/postgres:latest
    environment:
     - POSTGRES_PASSWORD=23894idhfkasjdhkhioydifad
    volumes:
     - data12:/var/lib/postgresql/data
    ports:
     - 5431:5432
  postgres_upg:
    image: pg94to12
    build: pg94to12
    environment:
     - POSTGRES_PASSWORD=23894idhfkasjdhkhioydifad
    volumes:
     - data94:/var/lib/postgresql/9.4/main
     - data12:/var/lib/postgresql/12/main
